### ISSUE TITLE
Request for Missing Code

### ISSUE THREAD

**Issue by enzeas** [sherryxuePKU/scNanoCOOL-seq#1]
I was attempting to use the preprocess.sh script from the repository, but it seems to be looking for a missing R script, specifically CpGProfile_merge_v2.R. This script appears to be crucial for the preprocessing workflow.

Could you please check if some script is missing from the repository? If possible, could you upload the missing scripts or provide guidance on where to obtain it? This would greatly assist in successfully running the preprocessing workflow.

Thank you for your assistance!

**Comment by xixueyu96** [comment]
hello enzeas, sorry for the missing scripts. I will supplement them as soon as possible.

**Comment by sherryxuePKU** [comment]
Hello enzeas~ Sorry for the missing scripts. I will supplement them as soon as possible.
